spring:
  application:
    name: minishop
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_shop?useSSL=false&serverTimezone=UTC
    username: root
    password: Liujinshuo985!
mybatis-plus:
  configuration:
    # ?? MyBatis ????? P6Spy ????
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
